"use client"; // This is a client component 👈🏽
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "../../components/header";
import Footer from "../../components/footer";

const inter = Inter({ subsets: ['latin'] })

 const metadata = {
  title: 'Front-end Test',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children, withHeader, withFooter }) {
  return (
    <main className="containner-fluid d-flex flex-column flex-fill vh-100">
      {withHeader && <Header />}
      {children}
      {withFooter && <Footer />}
    </main>
  )
}
